### ISSUE TITLE
bug when using avs 2.6

### ISSUE THREAD

**Issue by realfinder** [Asd-g/AviSynth-vsMSharpen#2]
![New File (9)000014 f](https://user-images.githubusercontent.com/2512153/83254119-e701dc00-a1b6-11ea-9b6a-3bc55d98b92f.png)
LoadPlugin("vsMSharpen.dll")
colorbars()
converttoyv12
Spline36Resize(880,496) #or any resizer
vsMSharpen
info

**Comment by realfinder** [comment]
same as MiniDeen and fixed by https://github.com/HomeOfAviSynthPlusEvolution/MiniDeen/commit/9a3c53a1f66d2943c2027dd209c2580763236507

**Comment by Asd-g** [comment]
Please try 2.0.1.

**Comment by realfinder** [comment]
that seems work, thanks
